modLoader = "javafml"
loaderVersion = "[61,)"
license = "ARR"
issueTrackerURL = "https://github.com/Kishku7/mod_support/issues"

[[mods]]
modId = "lavaboats"
version = "${file.jarVersion}"
displayName = "Lava Boats"
authors = "Kishku7"
description = '''
Adds Crimson and Warped boats (with chest variants) that ride on lava like water, never burn, and protect their passengers from fire.
'''
logoFile = "icon.png"

[[dependencies.lavaboats]]
    modId = "forge"
    mandatory = true
    versionRange = "[61,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.lavaboats]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.21.11,1.22)"
    ordering = "NONE"
    side = "BOTH"








































